### ISSUE TITLE
Mispelling on contributor's name on demo page

### ISSUE THREAD

**Issue by gladwearefriends** [tawny-owl/marketing-site#86]
![screen shot 2015-01-27 at 11 27 02 am](https://cloud.githubusercontent.com/assets/7787407/5925313/8276886c-a617-11e4-914b-1d2b15bab2cd.png)

I've been really curious as to who Catherine and Bui is, but after some intense googling i think its just one person her name is Catherine Bui. :smirk:

**Comment by WillSen** [comment]
:D changing
